import puppeteer from 'puppeteer';
const BASE='http://localhost:8080';
const b=await puppeteer.launch({headless:'new',args:['--no-sandbox']});
const ctx=await b.createBrowserContext(); const p=await ctx.newPage();
const [w,h]=(process.env.VP||'1440x900').split('x').map(Number);
await p.setViewport({width:w,height:h,isMobile:w<900,hasTouch:w<900});
await p.goto(BASE+'/login',{waitUntil:'networkidle2'});
await p.type('#email',process.env.U); await p.type('#password',process.env.PW||'Etpb@2026#Change');
await Promise.all([p.waitForNavigation({waitUntil:'networkidle2'}),p.click('button[type=submit]')]);
await p.goto(BASE+process.env.P,{waitUntil:'networkidle2'});
await p.screenshot({path:process.env.OUT});
console.log('scrollWidth',await p.evaluate(()=>document.documentElement.scrollWidth),'viewport',w);
await b.close();
